image:
  # => Windows Server 2012 R2
  - Visual Studio 2015
  # => Windows Server 2016
  - Visual Studio 2017

branches:
  only:
    - master
    - /^\d+\.\d+\.x$/ # Version branches like X.X.X
    - /^test-.*$/

install:
  # Fail fast if a newer build is queued for the same PR
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }
  # Use Python 3.7 by default
  - "SET PATH=C:\\Python37;C:\\Python37\\Scripts;%PATH%"
  # Check env
  - "python --version"
  # Upgrade pip to avoid warnings
  - "python -m pip install --upgrade pip"
  # Ready to install tox and coverage
  - "pip install tox codecov"

build: off

test_script:
  # As Python in PATH is 3.7, it is implicitly tested through tox 'cover' env.
  - tox -c tox-win.ini -e py34,py35,py36,cover

on_success:
  - codecov
