jobs:
  - job: extended_test
    variables:
      - name: IMAGE_NAME
        value: ubuntu-18.04
      - name: PYTHON_VERSION
        value: 3.10
      - group: certbot-common
    strategy:
      matrix:
        macos-farmtest-apache2:
          # We run one of these test farm tests on macOS to help ensure the
          # tests continue to work on the platform.
          IMAGE_NAME: macOS-10.15
          PYTHON_VERSION: 3.8
          TOXENV: test-farm-apache2
    pool:
      vmImage: $(IMAGE_NAME)
    steps:
      - template: ../steps/tox-steps.yml
