jobs:
  - job: extended_test
    variables:
      - name: IMAGE_NAME
        value: ubuntu-22.04
      - name: PYTHON_VERSION
        value: 3.12
      - group: certbot-common
    strategy:
      matrix:
        linux-py39:
          PYTHON_VERSION: 3.9
          TOXENV: py39
        linux-py310:
          PYTHON_VERSION: 3.10
          TOXENV: py310
        linux-py311:
          PYTHON_VERSION: 3.11
          TOXENV: py311
        linux-isolated:
          TOXENV: 'isolated-{acme,certbot,apache,cloudflare,digitalocean,dnsimple,dnsmadeeasy,gehirn,google,linode,luadns,nsone,ovh,rfc2136,route53,sakuracloud,nginx}'
        linux-boulder-v2-integration-certbot-oldest:
          PYTHON_VERSION: 3.8
          TOXENV: integration-certbot-oldest
          ACME_SERVER: boulder-v2
        linux-boulder-v2-integration-nginx-oldest:
          PYTHON_VERSION: 3.8
          TOXENV: integration-nginx-oldest
          ACME_SERVER: boulder-v2
        linux-boulder-v2-py38-integration:
          PYTHON_VERSION: 3.8
          TOXENV: integration
          ACME_SERVER: boulder-v2
        linux-boulder-v2-py39-integration:
          PYTHON_VERSION: 3.9
          TOXENV: integration
          ACME_SERVER: boulder-v2
        linux-boulder-v2-py310-integration:
          PYTHON_VERSION: 3.10
          TOXENV: integration
          ACME_SERVER: boulder-v2
        linux-boulder-v2-py311-integration:
          PYTHON_VERSION: 3.11
          TOXENV: integration
          ACME_SERVER: boulder-v2
        linux-boulder-v2-py312-integration:
          PYTHON_VERSION: 3.12
          TOXENV: integration
          ACME_SERVER: boulder-v2
        nginx-compat:
          TOXENV: nginx_compat
        linux-integration-rfc2136:
          IMAGE_NAME: ubuntu-22.04
          PYTHON_VERSION: 3.8
          TOXENV: integration-dns-rfc2136
        le-modification:
          IMAGE_NAME: ubuntu-22.04
          TOXENV: modification
        farmtest-apache2:
          PYTHON_VERSION: 3.8
          TOXENV: test-farm-apache2
    pool:
      vmImage: $(IMAGE_NAME)
    steps:
      - template: ../steps/tox-steps.yml
