jobs:
  - job: extended_test
    variables:
      - name: IMAGE_NAME
        value: ubuntu-22.04
      - name: PYTHON_VERSION
        value: 3.12
      - group: certbot-common
    strategy:
      matrix:
        linux-py39:
          PYTHON_VERSION: 3.9
          TOXENV: py39
        linux-py310:
          PYTHON_VERSION: 3.10
          TOXENV: py310
        linux-py311:
          PYTHON_VERSION: 3.11
          TOXENV: py311
        linux-isolated:
          TOXENV: 'isolated-acme,isolated-certbot,isolated-apache,isolated-cloudflare,isolated-digitalocean,isolated-dnsimple,isolated-dnsmadeeasy,isolated-gehirn,isolated-google,isolated-linode,isolated-luadns,isolated-nsone,isolated-ovh,isolated-rfc2136,isolated-route53,isolated-sakuracloud,isolated-nginx'
        linux-integration-certbot-oldest:
          PYTHON_VERSION: 3.8
          TOXENV: integration-certbot-oldest
        linux-integration-nginx-oldest:
          PYTHON_VERSION: 3.8
          TOXENV: integration-nginx-oldest
        linux-py38-integration:
          PYTHON_VERSION: 3.8
          TOXENV: integration
        linux-py39-integration:
          PYTHON_VERSION: 3.9
          TOXENV: integration
        linux-py310-integration:
          PYTHON_VERSION: 3.10
          TOXENV: integration
        linux-py311-integration:
          PYTHON_VERSION: 3.11
          TOXENV: integration
        linux-py312-integration:
          PYTHON_VERSION: 3.12
          TOXENV: integration
        nginx-compat:
          TOXENV: nginx_compat
        linux-integration-rfc2136:
          IMAGE_NAME: ubuntu-22.04
          PYTHON_VERSION: 3.8
          TOXENV: integration-dns-rfc2136
        le-modification:
          IMAGE_NAME: ubuntu-22.04
          TOXENV: modification
        farmtest-apache2:
          PYTHON_VERSION: 3.8
          TOXENV: test-farm-apache2
    pool:
      vmImage: $(IMAGE_NAME)
    steps:
      - template: ../steps/tox-steps.yml
