jobs:
  - job: extended_test
    variables:
      - name: IMAGE_NAME
        value: ubuntu-22.04
      - name: PYTHON_VERSION
        value: 3.10
      - group: certbot-common
    strategy:
      matrix:
        linux-boulder-v2-integration-certbot-oldest:
          PYTHON_VERSION: 3.7
          TOXENV: integration-certbot-oldest
          ACME_SERVER: boulder-v2
        linux-boulder-v2-integration-nginx-oldest:
          PYTHON_VERSION: 3.7
          TOXENV: integration-nginx-oldest
          ACME_SERVER: boulder-v2
        linux-boulder-v2-py37-integration:
          PYTHON_VERSION: 3.7
          TOXENV: integration
          ACME_SERVER: boulder-v2
        linux-boulder-v2-py38-integration:
          PYTHON_VERSION: 3.8
          TOXENV: integration
          ACME_SERVER: boulder-v2
        linux-boulder-v2-py39-integration:
          PYTHON_VERSION: 3.9
          TOXENV: integration
          ACME_SERVER: boulder-v2
        linux-boulder-v2-py310-integration:
          PYTHON_VERSION: 3.10
          TOXENV: integration
          ACME_SERVER: boulder-v2
        linux-integration-rfc2136:
          IMAGE_NAME: ubuntu-22.04
          PYTHON_VERSION: 3.8
          TOXENV: integration-dns-rfc2136
    pool:
      vmImage: $(IMAGE_NAME)
    steps:
      - template: ../steps/tox-steps.yml
