jobs:
  - job: x_test
    variables:
      IMAGE_NAME: ubuntu-18.04
      ${{ if contains(variables['TOXENV'], 'integration') }}:
        PYTEST_ADDOPTS: --numprocesses 4
    strategy:
      matrix:
        linux-py36:
          PYTHON_VERSION: 3.6
          TOXENV: py36
        linux-py37:
          PYTHON_VERSION: 3.7
          TOXENV: py37
        linux-py37-nopin:
          PYTHON_VERSION: 3.7
          TOXENV: py37
          CERTBOT_NO_PIN: 1
        linux-boulder-v1-integration-certbot:
          TOXENV: integration-certbot-oldest
          ACME_SERVER: boulder-v1
        linux-boulder-v2-integration-certbot:
          TOXENV: integration-certbot-oldest
          ACME_SERVER: boulder-v2
        linux-boulder-v1-integration-nginx:
          TOXENV: integration-nginx-oldest
          ACME_SERVER: boulder-v1
        linux-boulder-v2-integration-nginx:
          TOXENV: integration-nginx-oldest
          ACME_SERVER: boulder-v2
        linux-boulder-v1-py27-integration:
          PYTHON_VERSION: 2.7
          TOXENV: integration
          ACME_SERVER: boulder-v1
        linux-boulder-v2-py27-integration:
          PYTHON_VERSION: 2.7
          TOXENV: integration
          ACME_SERVER: boulder-v2
        linux-boulder-v1-py35-integration:
          PYTHON_VERSION: 3.5
          TOXENV: integration
          ACME_SERVER: boulder-v1
        linux-boulder-v2-py35-integration:
          PYTHON_VERSION: 3.5
          TOXENV: integration
          ACME_SERVER: boulder-v2
        linux-boulder-v1-py36-integration:
          PYTHON_VERSION: 3.6
          TOXENV: integration
          ACME_SERVER: boulder-v1
        linux-boulder-v2-py36-integration:
          PYTHON_VERSION: 3.6
          TOXENV: integration
          ACME_SERVER: boulder-v2
        linux-boulder-v1-py37-integration:
          PYTHON_VERSION: 3.7
          TOXENV: integration
          ACME_SERVER: boulder-v1
        linux-boulder-v2-py37-integration:
          PYTHON_VERSION: 3.7
          TOXENV: integration
          ACME_SERVER: boulder-v2
        linux-boulder-v1-py38-integration:
          PYTHON_VERSION: 3.8
          TOXENV: integration
          ACME_SERVER: boulder-v1
        linux-boulder-v2-py38-integration:
          PYTHON_VERSION: 3.8
          TOXENV: integration
          ACME_SERVER: boulder-v2
        nginx-compat:
          TOXENV: nginx_compat
        le-auto-jessie:
          TOXENV: le_auto_jessie
        le-auto-centos6:
          TOXENV: le_auto_centos6
        le-auto-oraclelinux6:
          TOXENV: le_auto_oraclelinux6
        dev:
          TOXENV: docker_dev
    pool:
      vmImage: $(IMAGE_NAME)
    steps:
      - template: tox-steps.yml
