stages:
  - stage: Deploy
    jobs:
      - job: create_github_release
        pool:
          vmImage: ubuntu-22.04
        steps:
        - task: DownloadPipelineArtifact@2
          inputs:
            artifact: changelog
            path: '$(Pipeline.Workspace)'
        - task: GitHubRelease@1
          inputs:
            gitHubConnection: github-releases
            title: 'Certbot $(Build.SourceBranchName)'
            releaseNotesFilePath: '$(Pipeline.Workspace)/release_notes.md'
            assets: '$(Build.SourcesDirectory)/packages/{*.tar.gz,SHA256SUMS*}'
            addChangeLog: false
            isDraft: true  # this is just for testing
