language: python
before_install:
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends install nginx-light python3-venv
  - sudo -E /etc/init.d/nginx stop
install:
  - sudo /snap/bin/lxd.migrate -yes
  - sudo /snap/bin/lxd waitready
  - sudo /snap/bin/lxd init --auto
  - git clone https://github.com/certbot/certbot.git certbot --branch master
  - certbot/tools/strip_hashes.py certbot/letsencrypt-auto-source/pieces/dependency-requirements.txt > certbot/constraints.txt
before_script:
  - sudo snapcraft --use-lxd
script:
  - sudo snap install --dangerous --classic *.snap
  - sudo bash test.sh
deploy:
  'on':
    branch: master
  provider: snap
  snap: certbot_*.snap
  channel: edge
  skip_cleanup: true
notifications:
  email:
    recipients: [robie.basak@canonical.com]
    on_failure: change
addons:
  snaps:
    - name: snapcraft
      channel: stable
      classic: true
    - name: lxd
      channel: stable
