# Advanced pipeline for isolated checks and release purpose
trigger:
  - test-*
  - '*.x'
pr:
  - test-*
  - '*.x'
# This pipeline is also nightly run on master
schedules:
  - cron: "0 4 * * *"
    displayName: Nightly build
    branches:
      include:
      - master
    always: true

jobs:
  # Any addition here should be reflected in the release pipeline.
  # It is advised to declare all jobs here as templates to improve maintainability.
  - template: templates/tests-suite.yml
  - template: templates/installer-tests.yml
